"""add initial models

Revision ID: 53c21c9e330b
Revises: 
Create Date: 2022-05-29 23:03:30.560913

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "53c21c9e330b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("channel", sa.String(length=255), nullable=True),
        sa.Column("execute_at", sa.DateTime(), nullable=False),
        sa.Column("repeat", sa.Boolean(), nullable=True),
        sa.Column("repeat_every", sa.BigInteger(), nullable=False),
        sa.Column("repeat_until", sa.DateTime(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
